#!/bin/bash
# bootstrap/checkin.sh
# Registers this node with the platform control plane.
# Installs a self-cleaning periodic cron job.
set -euo pipefail

log() { echo "[checkin] $*"; }

CONTROL_PLANE_URL="${CONTROL_PLANE_URL:?CONTROL_PLANE_URL is required}"
CALLBACK_TOKEN="${CALLBACK_TOKEN:?CALLBACK_TOKEN is required}"
ENVIRONMENT_ID="${ENVIRONMENT_ID:?ENVIRONMENT_ID is required}"
AGENT_VERSION="${AGENT_VERSION:-0.1.0}"

HOSTNAME=$(hostname -f 2>/dev/null || hostname)

# Prefer IP injected from tofu outputs (reliable, no network dependency)
if [ -n "${ENV_PUBLIC_IP:-}" ] && [ "$ENV_PUBLIC_IP" != "203.0.113.10" ]; then
  PUBLIC_IP="$ENV_PUBLIC_IP"
  log "Using IP from tofu outputs: $PUBLIC_IP"
else
  PUBLIC_IP=$(curl -sf --max-time 5 https://api.ipify.org || echo "unknown")
  log "Using IP from ipify: $PUBLIC_IP"
fi

do_checkin() {
  curl -sf -X POST "${CONTROL_PLANE_URL}/api/nodes/checkin" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${CALLBACK_TOKEN}" \
    -d "{
      \"environment_id\": \"${ENVIRONMENT_ID}\",
      \"hostname\": \"${HOSTNAME}\",
      \"public_ip\": \"${PUBLIC_IP}\",
      \"agent_version\": \"${AGENT_VERSION}\"
    }"
}

log "Registering node..."
log "  Environment: $ENVIRONMENT_ID"
log "  Hostname:    $HOSTNAME"
log "  Public IP:   $PUBLIC_IP"

do_checkin
log "Node registered successfully."

# ── Install self-cleaning periodic cron job ───────────────────────────────────
CRON_SCRIPT="/usr/local/bin/platform-checkin.sh"

log "Installing periodic checkin cron job..."

cat > "$CRON_SCRIPT" << EOF
#!/bin/bash
# Auto-generated by platform-infra checkin.sh
# Periodic node health check-in to control plane
# Self-cleans when environment is destroyed
CONTROL_PLANE_URL="${CONTROL_PLANE_URL}"
CALLBACK_TOKEN="${CALLBACK_TOKEN}"
ENVIRONMENT_ID="${ENVIRONMENT_ID}"
AGENT_VERSION="${AGENT_VERSION}"
HOSTNAME=\$(hostname -f 2>/dev/null || hostname)
PUBLIC_IP="${PUBLIC_IP}"
CRON_SCRIPT="/usr/local/bin/platform-checkin.sh"

# Check if environment still exists -- if not, self-destruct
HTTP_STATUS=\$(curl -s -o /dev/null -w "%{http_code}" \\
  "\${CONTROL_PLANE_URL}/api/environments/\${ENVIRONMENT_ID}/exists" \\
  -H "Authorization: Bearer \${CALLBACK_TOKEN}" 2>/dev/null || echo "000")

if [ "\$HTTP_STATUS" = "404" ] || [ "\$HTTP_STATUS" = "000" ]; then
  # Environment gone — remove cron job and script
  ( crontab -l 2>/dev/null | grep -v "platform-checkin" ) | crontab - 2>/dev/null || true
  rm -f "\$CRON_SCRIPT"
  exit 0
fi

# Environment exists — do checkin
curl -sf -X POST "\${CONTROL_PLANE_URL}/api/nodes/checkin" \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer \${CALLBACK_TOKEN}" \\
  -d "{
    \"environment_id\": \"\${ENVIRONMENT_ID}\",
    \"hostname\": \"\${HOSTNAME}\",
    \"public_ip\": \"\${PUBLIC_IP}\",
    \"agent_version\": \"\${AGENT_VERSION}\"
  }" > /dev/null 2>&1
EOF

chmod +x "$CRON_SCRIPT"

# Add to cron — every 5 minutes
CRON_ENTRY="*/5 * * * * $CRON_SCRIPT"
( crontab -l 2>/dev/null | grep -v "platform-checkin"; echo "$CRON_ENTRY" ) | crontab -

log "Cron job installed: every 5 minutes (self-cleaning)"
